app:
  prompt:
    templates:
      context: "Context: {context}"
      functioncall: "Use tools with /commands when needed"
    scenarios:
      rag:
        system: "Answer using this information: {context}"
      mcp:
        system: "Conversation so far: {history}"
